### ISSUE TITLE
12 検索機能実装

### ISSUE THREAD

**Issue by kazufoot21** [minty1202/kensyu#25]
# Why

特定のTodo、Userを検索できるようにするため

# What
UserとTodoを検索できるようにする
検索後は、検索結果一覧ページを表示
リクエストテスト記述

**Comment by minty1202** [comment]
どのコントローラでどのように行うかも教えてください

**Comment by kazufoot21** [comment]
User、Todoモデル内で、完全一致などの条件で取得する処理を記述
searchコントローラー作成し、モデル内で定義した処理を使って検索内容を取得

上記で考えています。

**Comment by minty1202** [comment]
> searchコントローラー作成し、モデル内で定義した処理を使って検索内容を取得

わざわざコントローラを作る必要もない気がしますが、まぁいいか。
恐らく同じような記述が増えると思うのでミックスイン等上手く活用して保守性を高くなるよう努めてください。

**Comment by minty1202** [comment]
進めていただいて大丈夫です

**Comment by kazufoot21** [comment]
承知致しました。
