### ISSUE TITLE
16 終了期限

### ISSUE THREAD

**Issue by kazufoot21** [minty1202/kensyu#31]
# Why
消化出来ていないTodoを判断するため

# What
Todoを登録するときに終了期限を設ける
終了期限の更新ができるようにする
status（todo, doing, done）に分けれるようにする
mypageにて3つのステータスを分けて表示できるようにする

一覧ページ 終了期限の近い順に順番を変える

**Comment by minty1202** [comment]
status の todo って何のためにあるのでしょうか？
例えば日本語で表すなら 未完了：完了済みの二つで事足りそうな気がします。
もしtodoを使うのであればもう少し用途のわかりやすい命名にしてください。

**Comment by kazufoot21** [comment]
todoは手をつけていないものを表したかったのですが、2つのほうがシンプルですね。
未完了：完了済みの二つで実装したいと思います。

**Comment by minty1202** [comment]
penddingとか？

**Comment by kazufoot21** [comment]
pendingは思いつきませんでした！
ステータスだけ英語になるのも変なので、未完了、進行中、完了でもいいかなと思いました。

**Comment by minty1202** [comment]
いや、コード上は英語でも問題ないのですが、どう管理するかの話ですね。
完了、未完了であればbooleanで済みますが
三つ以上になるとenumを使うことになるので前田さんとしてどうしたいかが知りたかったです。
