### ISSUE TITLE
17 タグ付け機能

### ISSUE THREAD

**Issue by kazufoot21** [minty1202/kensyu#32]
# Why
Todoに対してタグをつける

# What
User側がTodoに対して複数のタグを作れるようにする
Todo作成時にタグを付けれるようにする
編集ができるようにする
mypageにタグの一覧を表示、リンクでタグごとのページに飛べるようにする

中間テーブル作成
Todo：タグ ＝多：多

**Comment by minty1202** [comment]
ER図ください

**Comment by kazufoot21** [comment]
@minty1202 
ご確認お願いします。

![tag Diagram drawio](https://user-images.githubusercontent.com/73515602/170660158-edbb4b23-a838-4b9b-abc3-92da03232238.png)

**Comment by kazufoot21** [comment]
@minty1202 
ご確認お願いします。

![tag Diagram drawio (1)](https://user-images.githubusercontent.com/73515602/170660881-1d298365-d8be-4ced-8897-351af2f05541.png)

**Comment by minty1202** [comment]
~~中間テーブルいる？~~

**Comment by minty1202** [comment]
かしこまりました。
カラム名だけ tagname ではなく nameにしてもらえれば大丈夫です。

**Comment by kazufoot21** [comment]
承知しました。ありがとうございます。
