### ISSUE TITLE
issue22 タグ投稿機能 新しいタグ（入力）の既存タグ（チェックボックス）

### ISSUE THREAD

**Issue by kazufoot21** [minty1202/kensyu#44]
# Why
文字の前後にスペースがあるタグとないタグは同じタグとするため

[hoge, fuga] と [hoge,    &emsp;&emsp; fuga  ] は現状だと別物。
現状だと hoge, fuga,   &emsp;&emsp;fuga の3つのタグができてしまう

# What

view 
[memo]
タグの追加ができるようにする
collection_check_boxesでチェックボックスとタグ名を表示

Todoの作成、編集画面でタグの追加を作成 (_form.html.slim)
保存したら、collection_check_boxesでチェックボックスとタグ名を表示を表示させる
作成、更新時はチェックがついているものをそのTodoのタグとする

**Comment by minty1202** [comment]
空白にするのもそうだけど
タグの選択ないし入力はチェックボックスにするのが妥当な気はする

**Comment by minty1202** [comment]
あとwhatに書かれている内容はwhyにあたるからwhatにはどうやってやるのかが書けるといいと思います。
今回はいいです。
